rvm:
 - 1.9.3
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential freeglut3-dev libfreeimage-dev libgl1-mesa-dev libopenal-dev libpango1.0-dev libsdl-ttf2.0-dev libsndfile-dev libxinerama-dev
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - cd test && bundle exec rspec *
addons:
  code_climate:
    repo_token: 9d20f21fc1b16cadd10b7962abc77594fae7c6db52b86a1
